name: Build and Test MAUI iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # ¨Ï¥Î .NET 8

      - name: Install MAUI workloads
        run: dotnet workload install maui-ios maui-android maui-maccatalyst

      - name: Install dependencies
        run: dotnet restore src/MauiApp1/MauiApp1.csproj

      - name: Build the project
        run: dotnet build --configuration Release -f net8.0-ios src/MauiApp1/MauiApp1.csproj
