name: Build and Publish MAUI iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'

      - name: Install MAUI workloads
        run: dotnet workload install maui-ios maui-android maui-maccatalyst

      - name: Install dependencies
        run: dotnet restore src/MauiApp1/MauiApp1.csproj

      - name: Build the project
        run: dotnet build --configuration Release -f net8.0-ios src/MauiApp1/MauiApp1.csproj

      - name: Package the app
        run: |
          mkdir -p output
          cp -r src/MauiApp1/bin/Release/net8.0-ios/iossimulator-arm64/* output/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mauiapp1-ios
          path: output/

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_CREDENTIALS }}
          GITHUB_ACTOR: ${{ secrets.DEPLOY_ACCOUNT }}
        run: |
          echo "Publishing to GitHub Packages"
          dotnet nuget push output/*.nupkg --source https://nuget.pkg.github.com/${{ secrets.DEPLOY_ACCOUNT }}/index.json --api-key ${{ secrets.DEPLOY_CREDENTIALS }}
