name: Build and Publish MAUI iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'

      - name: Install MAUI workloads
        run: dotnet workload install maui-ios maui-android maui-maccatalyst

      - name: Install dependencies
        run: dotnet restore src/MauiApp1/MauiApp1.csproj

      - name: Build the project
        run: dotnet build --configuration Release -f net8.0-ios src/MauiApp1/MauiApp1.csproj

      - name: Publish the project
        run: dotnet publish src/MauiApp1/MauiApp1.csproj -c Release -f net8.0-ios -o output --runtime ios-arm64 --self-contained true /p:ArchiveOnBuild=true

      - name: Package the app
        run: |
          mkdir -p output/ipa
          cp output/*.ipa output/ipa/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mauiapp1-ios
          path: output/ipa/*.ipa

      - name: Install GitHub CLI
        run: brew install gh

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_CREDENTIALS }}
          GITHUB_ACTOR: ${{ secrets.DEPLOY_ACCOUNT }}
        run: |
          echo "Publishing to GitHub Packages"
          gh release create "release-$(date +'%Y%m%d%H%M%S')" output/ipa/*.ipa --repo MDPNetCore/MDP.Lab --title "Release $(date +'%Y-%m-%d %H:%M:%S')" --notes "Automated release from GitHub Actions"
